### ISSUE TITLE
Live game API - outdated schemas

### ISSUE THREAD

**Issue by diogotr7** [MingweiSamuel/Camille#60]
I'm having some trouble using the `Camille.LolGame` version `3.0.0-nightly-2021-10-13-2db3603136` package. 
Exception:
```
System.Text.Json.JsonException
  HResult=0x80131500
  Message=The JSON value could not be converted to System.Int32. Path: $.activePlayer.championStats.armor | LineNumber: 41 | BytePositionInLine: 29.
  Source=System.Text.Json
  StackTrace:
   at System.Text.Json.ThrowHelper.ReThrowWithPath(ReadStack& state, Utf8JsonReader& reader, Exception ex) in /_/src/libraries/System.Text.Json/src/System/Text/Json/ThrowHelper.Serialization.cs:line 314
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state) in /_/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/JsonConverterOfT.ReadCore.cs:line 85
   at System.Text.Json.JsonSerializer.ReadCore[TValue](JsonConverter jsonConverter, Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state) in /_/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/JsonSerializer.Read.Helpers.cs:line 35
   at System.Text.Json.JsonSerializer.ReadCore[TValue](Utf8JsonReader& reader, Type returnType, JsonSerializerOptions options) in /_/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/JsonSerializer.Read.Helpers.cs:line 21
   at System.Text.Json.JsonSerializer.Deserialize[TValue](String json, Type returnType, JsonSerializerOptions options) in /_/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/JsonSerializer.Read.String.cs:line 113
   at System.Text.Json.JsonSerializer.Deserialize[TValue](String json, JsonSerializerOptions options) in /_/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/JsonSerializer.Read.String.cs:line 44
   at Camille.Core.JsonHandler.Deserialize[T](String content)
   at Camille.LolGame.LolGameApi.<Send>d__7`1.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() in /_/src/libraries/System.Private.CoreLib/src/System/Runtime/ExceptionServices/ExceptionDispatchInfo.cs:line 56
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) in /_/src/libraries/System.Private.CoreLib/src/System/Runtime/CompilerServices/TaskAwaiter.cs:line 173
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) in /_/src/libraries/System.Private.CoreLib/src/System/Runtime/CompilerServices/TaskAwaiter.cs:line 150
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult() in /_/src/libraries/System.Private.CoreLib/src/System/Runtime/CompilerServices/TaskAwaiter.cs:line 364
   at CamillePlayground.Program.<Main>d__0.MoveNext() in D:\Source\CamillePlayground\Program.cs:line 19
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() in /_/src/libraries/System.Private.CoreLib/src/System/Runtime/ExceptionServices/ExceptionDispatchInfo.cs:line 56
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) in /_/src/libraries/System.Private.CoreLib/src/System/Runtime/CompilerServices/TaskAwaiter.cs:line 173
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) in /_/src/libraries/System.Private.CoreLib/src/System/Runtime/CompilerServices/TaskAwaiter.cs:line 150
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult() in /_/src/libraries/System.Private.CoreLib/src/System/Runtime/CompilerServices/TaskAwaiter.cs:line 105
   at CamillePlayground.Program.<Main>(String[] args)

  This exception was originally thrown at this call stack:
    System.Text.Json.Utf8JsonReader.GetInt32() in Utf8JsonReader.TryGet.cs
    Camille.Core.JsonHandler.CustomIntConverter.Read(ref System.Text.Json.Utf8JsonReader, System.Type, System.Text.Json.JsonSerializerOptions)
    System.Text.Json.Serialization.JsonConverter<T>.TryRead(ref System.Text.Json.Utf8JsonReader, System.Type, System.Text.Json.JsonSerializerOptions, ref System.Text.Json.ReadStack, out T) in JsonConverterOfT.cs
    System.Text.Json.JsonPropertyInfo<T>.ReadJsonAndSetMember(object, ref System.Text.Json.ReadStack, ref System.Text.Json.Utf8JsonReader) in JsonPropertyInfoOfT.cs
    System.Text.Json.Serialization.Converters.ObjectDefaultConverter<T>.OnTryRead(ref System.Text.Json.Utf8JsonReader, System.Type, System.Text.Json.JsonSerializerOptions, ref System.Text.Json.ReadStack, out T) in ObjectDefaultConverter.cs
    System.Text.Json.Serialization.JsonConverter<T>.TryRead(ref System.Text.Json.Utf8JsonReader, System.Type, System.Text.Json.JsonSerializerOptions, ref System.Text.Json.ReadStack, out T) in JsonConverterOfT.cs
    System.Text.Json.JsonPropertyInfo<T>.ReadJsonAndSetMember(object, ref System.Text.Json.ReadStack, ref System.Text.Json.Utf8JsonReader) in JsonPropertyInfoOfT.cs
    System.Text.Json.Serialization.Converters.ObjectDefaultConverter<T>.OnTryRead(ref System.Text.Json.Utf8JsonReader, System.Type, System.Text.Json.JsonSerializerOptions, ref System.Text.Json.ReadStack, out T) in ObjectDefaultConverter.cs
    System.Text.Json.Serialization.JsonConverter<T>.TryRead(ref System.Text.Json.Utf8JsonReader, System.Type, System.Text.Json.JsonSerializerOptions, ref System.Text.Json.ReadStack, out T) in JsonConverterOfT.cs
    System.Text.Json.JsonPropertyInfo<T>.ReadJsonAndSetMember(object, ref System.Text.Json.ReadStack, ref System.Text.Json.Utf8JsonReader) in JsonPropertyInfoOfT.cs
    ...
    [Call Stack Truncated]

Inner Exception 1:
FormatException: Either the JSON value is not in a supported format, or is out of bounds for an Int32.

```

Json response from the game:
```json
{
	"activePlayer": {
		"abilities": {
			"E": {
				"abilityLevel": 5,
				"displayName": "Evolved Leap",
				"id": "KhazixELong",
				"rawDescription": "GeneratedTip_InheritedSpell_KhazixELong_Description",
				"rawDisplayName": "GeneratedTip_InheritedSpell_KhazixELong_DisplayName"
			},
			"Passive": {
				"displayName": "Unseen Threat",
				"id": "KhazixPassive",
				"rawDescription": "GeneratedTip_Passive_KhazixPassive_Description",
				"rawDisplayName": "GeneratedTip_Passive_KhazixPassive_DisplayName"
			},
			"Q": {
				"abilityLevel": 5,
				"displayName": "Evolved Taste Their Fear",
				"id": "KhazixQLong",
				"rawDescription": "GeneratedTip_InheritedSpell_KhazixQLong_Description",
				"rawDisplayName": "GeneratedTip_InheritedSpell_KhazixQLong_DisplayName"
			},
			"R": {
				"abilityLevel": 3,
				"displayName": "Void Assault",
				"id": "KhazixR",
				"rawDescription": "GeneratedTip_Spell_KhazixR_Description",
				"rawDisplayName": "GeneratedTip_Spell_KhazixR_DisplayName"
			},
			"W": {
				"abilityLevel": 5,
				"displayName": "Void Spike",
				"id": "KhazixW",
				"rawDescription": "GeneratedTip_Spell_KhazixW_Description",
				"rawDisplayName": "GeneratedTip_Spell_KhazixW_DisplayName"
			}
		},
		"championStats": {
			"abilityHaste": 8.0,
			"abilityPower": 0.0,
			"armor": 93.00000762939453,
			"armorPenetrationFlat": 0.0,
			"armorPenetrationPercent": 1.0,
			"attackDamage": 115.70000457763672,
			"attackRange": 175.0,
			"attackSpeed": 0.9746120572090149,
			"bonusArmorPenetrationPercent": 1.0,
			"bonusMagicPenetrationPercent": 1.0,
			"critChance": 0.0,
			"critDamage": 175.0,
			"currentHealth": 2158.0,
			"healShieldPower": 0.0,
			"healthRegenRate": 4.050000190734863,
			"lifeSteal": 0.0,
			"magicLethality": 0.0,
			"magicPenetrationFlat": 0.0,
			"magicPenetrationPercent": 1.0,
			"magicResist": 53.25,
			"maxHealth": 2158.0,
			"moveSpeed": 350.0,
			"omnivamp": 0.0,
			"physicalLethality": 0.0,
			"physicalVamp": 0.0,
			"resourceMax": 1007.0000610351563,
			"resourceRegenRate": 3.2180001735687258,
			"resourceType": "MANA",
			"resourceValue": 1007.0000610351563,
			"spellVamp": 0.0,
			"tenacity": 0.0
		},
		"currentGold": 60473.22265625,
		"fullRunes": {
			"generalRunes": [
				{
					"displayName": "Grasp of the Undying",
					"id": 8437,
					"rawDescription": "perk_tooltip_GraspOfTheUndying",
					"rawDisplayName": "perk_displayname_GraspOfTheUndying"
				},
				{
					"displayName": "Font of Life",
					"id": 8463,
					"rawDescription": "perk_tooltip_FontOfLife",
					"rawDisplayName": "perk_displayname_FontOfLife"
				},
				{
					"displayName": "Conditioning",
					"id": 8429,
					"rawDescription": "perk_tooltip_Conditioning",
					"rawDisplayName": "perk_displayname_Conditioning"
				},
				{
					"displayName": "Revitalize",
					"id": 8453,
					"rawDescription": "perk_tooltip_Revitalize",
					"rawDisplayName": "perk_displayname_Revitalize"
				},
				{
					"displayName": "Cosmic Insight",
					"id": 8347,
					"rawDescription": "perk_tooltip_CosmicInsight",
					"rawDisplayName": "perk_displayname_CosmicInsight"
				},
				{
					"displayName": "Magical Footwear",
					"id": 8304,
					"rawDescription": "perk_tooltip_MagicalFootwear",
					"rawDisplayName": "perk_displayname_MagicalFootwear"
				}
			],
			"keystone": {
				"displayName": "Grasp of the Undying",
				"id": 8437,
				"rawDescription": "perk_tooltip_GraspOfTheUndying",
				"rawDisplayName": "perk_displayname_GraspOfTheUndying"
			},
			"primaryRuneTree": {
				"displayName": "Resolve",
				"id": 8400,
				"rawDescription": "perkstyle_tooltip_7204",
				"rawDisplayName": "perkstyle_displayname_7204"
			},
			"secondaryRuneTree": {
				"displayName": "Inspiration",
				"id": 8300,
				"rawDescription": "perkstyle_tooltip_7203",
				"rawDisplayName": "perkstyle_displayname_7203"
			},
			"statRunes": [
				{
					"id": 5007,
					"rawDescription": "perk_tooltip_StatModCooldownReductionScaling"
				},
				{
					"id": 5002,
					"rawDescription": "perk_tooltip_StatModArmor"
				},
				{
					"id": 5001,
					"rawDescription": "perk_tooltip_StatModHealthScaling"
				}
			]
		},
		"level": 18,
		"summonerName": "DrMeteor"
	},
	"allPlayers": [
		{
			"championName": "Kha'Zix",
			"isBot": false,
			"isDead": false,
			"items": [],
			"level": 18,
			"position": "",
			"rawChampionName": "game_character_displayname_Khazix",
			"rawSkinName": "game_character_skin_displayname_Khazix_4",
			"respawnTimer": 0.0,
			"runes": {
				"keystone": {
					"displayName": "Grasp of the Undying",
					"id": 8437,
					"rawDescription": "perk_tooltip_GraspOfTheUndying",
					"rawDisplayName": "perk_displayname_GraspOfTheUndying"
				},
				"primaryRuneTree": {
					"displayName": "Resolve",
					"id": 8400,
					"rawDescription": "perkstyle_tooltip_7204",
					"rawDisplayName": "perkstyle_displayname_7204"
				},
				"secondaryRuneTree": {
					"displayName": "Inspiration",
					"id": 8300,
					"rawDescription": "perkstyle_tooltip_7203",
					"rawDisplayName": "perkstyle_displayname_7203"
				}
			},
			"scores": {
				"assists": 0,
				"creepScore": 0,
				"deaths": 0,
				"kills": 0,
				"wardScore": 0.0
			},
			"skinID": 4,
			"skinName": "Dark Star Kha'Zix",
			"summonerName": "DrMeteor",
			"summonerSpells": {
				"summonerSpellOne": {
					"displayName": "Flash",
					"rawDescription": "GeneratedTip_SummonerSpell_SummonerFlash_Description",
					"rawDisplayName": "GeneratedTip_SummonerSpell_SummonerFlash_DisplayName"
				},
				"summonerSpellTwo": {
					"displayName": "Smite",
					"rawDescription": "GeneratedTip_SummonerSpell_SummonerSmite_Description",
					"rawDisplayName": "GeneratedTip_SummonerSpell_SummonerSmite_DisplayName"
				}
			},
			"team": "ORDER"
		}
	],
	"events": {
		"Events": [
			{
				"EventID": 0,
				"EventName": "GameStart",
				"EventTime": 0.01970990002155304
			},
			{
				"EventID": 1,
				"EventName": "MinionsSpawning",
				"EventTime": 65.03056335449219
			}
		]
	},
	"gameData": {
		"gameMode": "PRACTICETOOL",
		"gameTime": 140.5828857421875,
		"mapName": "Map11",
		"mapNumber": 11,
		"mapTerrain": "Default"
	}
}
```

Please let me know if there's any other useful information I should provide.

**Comment by MingweiSamuel** [comment]
Should be fixed in https://www.nuget.org/packages/Camille.LolGame/3.0.0-nightly-2021-10-24-5b49900ed6, let me know if you have any other issues!

**Comment by diogotr7** [comment]
I just tested again, it seems i have another very similar issue, with critChance instead:
```
System.Text.Json.JsonException
  HResult=0x80131500
  Message=The JSON value could not be converted to System.Int32. Path: $.activePlayer.championStats.critChance | LineNumber: 49 | BytePositionInLine: 36.
  Source=System.Text.Json
  StackTrace:
   at System.Text.Json.ThrowHelper.ReThrowWithPath(ReadStack& state, Utf8JsonReader& reader, Exception ex) in /_/src/libraries/System.Text.Json/src/System/Text/Json/ThrowHelper.Serialization.cs:line 314
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state) in /_/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/JsonConverterOfT.ReadCore.cs:line 85
   at System.Text.Json.JsonSerializer.ReadCore[TValue](JsonConverter jsonConverter, Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state) in /_/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/JsonSerializer.Read.Helpers.cs:line 35
   at System.Text.Json.JsonSerializer.ReadCore[TValue](Utf8JsonReader& reader, Type returnType, JsonSerializerOptions options) in /_/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/JsonSerializer.Read.Helpers.cs:line 21
   at System.Text.Json.JsonSerializer.Deserialize[TValue](String json, Type returnType, JsonSerializerOptions options) in /_/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/JsonSerializer.Read.String.cs:line 113
   at System.Text.Json.JsonSerializer.Deserialize[TValue](String json, JsonSerializerOptions options) in /_/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/JsonSerializer.Read.String.cs:line 44
   at Camille.Core.JsonHandler.Deserialize[T](String content)
   at Camille.LolGame.LolGameApi.<Send>d__7`1.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() in /_/src/libraries/System.Private.CoreLib/src/System/Runtime/ExceptionServices/ExceptionDispatchInfo.cs:line 56
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) in /_/src/libraries/System.Private.CoreLib/src/System/Runtime/CompilerServices/TaskAwaiter.cs:line 173
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) in /_/src/libraries/System.Private.CoreLib/src/System/Runtime/CompilerServices/TaskAwaiter.cs:line 150
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult() in /_/src/libraries/System.Private.CoreLib/src/System/Runtime/CompilerServices/TaskAwaiter.cs:line 364
   at CamillePlayground.Program.<Main>d__0.MoveNext() in D:\Source\CamillePlayground\Program.cs:line 18
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() in /_/src/libraries/System.Private.CoreLib/src/System/Runtime/ExceptionServices/ExceptionDispatchInfo.cs:line 56
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) in /_/src/libraries/System.Private.CoreLib/src/System/Runtime/CompilerServices/TaskAwaiter.cs:line 173
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) in /_/src/libraries/System.Private.CoreLib/src/System/Runtime/CompilerServices/TaskAwaiter.cs:line 150
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult() in /_/src/libraries/System.Private.CoreLib/src/System/Runtime/CompilerServices/TaskAwaiter.cs:line 105
   at CamillePlayground.Program.<Main>(String[] args)

  This exception was originally thrown at this call stack:
    System.Text.Json.Utf8JsonReader.GetInt32() in Utf8JsonReader.TryGet.cs
    Camille.Core.JsonHandler.CustomIntConverter.Read(ref System.Text.Json.Utf8JsonReader, System.Type, System.Text.Json.JsonSerializerOptions)
    System.Text.Json.Serialization.JsonConverter<T>.TryRead(ref System.Text.Json.Utf8JsonReader, System.Type, System.Text.Json.JsonSerializerOptions, ref System.Text.Json.ReadStack, out T) in JsonConverterOfT.cs
    System.Text.Json.JsonPropertyInfo<T>.ReadJsonAndSetMember(object, ref System.Text.Json.ReadStack, ref System.Text.Json.Utf8JsonReader) in JsonPropertyInfoOfT.cs
    System.Text.Json.Serialization.Converters.ObjectDefaultConverter<T>.OnTryRead(ref System.Text.Json.Utf8JsonReader, System.Type, System.Text.Json.JsonSerializerOptions, ref System.Text.Json.ReadStack, out T) in ObjectDefaultConverter.cs
    System.Text.Json.Serialization.JsonConverter<T>.TryRead(ref System.Text.Json.Utf8JsonReader, System.Type, System.Text.Json.JsonSerializerOptions, ref System.Text.Json.ReadStack, out T) in JsonConverterOfT.cs
    System.Text.Json.JsonPropertyInfo<T>.ReadJsonAndSetMember(object, ref System.Text.Json.ReadStack, ref System.Text.Json.Utf8JsonReader) in JsonPropertyInfoOfT.cs
    System.Text.Json.Serialization.Converters.ObjectDefaultConverter<T>.OnTryRead(ref System.Text.Json.Utf8JsonReader, System.Type, System.Text.Json.JsonSerializerOptions, ref System.Text.Json.ReadStack, out T) in ObjectDefaultConverter.cs
    System.Text.Json.Serialization.JsonConverter<T>.TryRead(ref System.Text.Json.Utf8JsonReader, System.Type, System.Text.Json.JsonSerializerOptions, ref System.Text.Json.ReadStack, out T) in JsonConverterOfT.cs
    System.Text.Json.JsonPropertyInfo<T>.ReadJsonAndSetMember(object, ref System.Text.Json.ReadStack, ref System.Text.Json.Utf8JsonReader) in JsonPropertyInfoOfT.cs
    ...
    [Call Stack Truncated]

Inner Exception 1:
FormatException: Either the JSON value is not in a supported format, or is out of bounds for an Int32.
```

```json
{
	"activePlayer": {
		"abilities": {
			"E": {
				"abilityLevel": 5,
				"displayName": "Evolved Leap",
				"id": "KhazixELong",
				"rawDescription": "GeneratedTip_InheritedSpell_KhazixELong_Description",
				"rawDisplayName": "GeneratedTip_InheritedSpell_KhazixELong_DisplayName"
			},
			"Passive": {
				"displayName": "Unseen Threat",
				"id": "KhazixPassive",
				"rawDescription": "GeneratedTip_Passive_KhazixPassive_Description",
				"rawDisplayName": "GeneratedTip_Passive_KhazixPassive_DisplayName"
			},
			"Q": {
				"abilityLevel": 5,
				"displayName": "Evolved Taste Their Fear",
				"id": "KhazixQLong",
				"rawDescription": "GeneratedTip_InheritedSpell_KhazixQLong_Description",
				"rawDisplayName": "GeneratedTip_InheritedSpell_KhazixQLong_DisplayName"
			},
			"R": {
				"abilityLevel": 3,
				"displayName": "Void Assault",
				"id": "KhazixR",
				"rawDescription": "GeneratedTip_Spell_KhazixR_Description",
				"rawDisplayName": "GeneratedTip_Spell_KhazixR_DisplayName"
			},
			"W": {
				"abilityLevel": 5,
				"displayName": "Void Spike",
				"id": "KhazixW",
				"rawDescription": "GeneratedTip_Spell_KhazixW_Description",
				"rawDisplayName": "GeneratedTip_Spell_KhazixW_DisplayName"
			}
		},
		"championStats": {
			"abilityHaste": 85.0,
			"abilityPower": 0.0,
			"armor": 87.00000762939453,
			"armorPenetrationFlat": 0.0,
			"armorPenetrationPercent": 1.0,
			"attackDamage": 401.5,
			"attackRange": 175.0,
			"attackSpeed": 0.9746120572090149,
			"bonusArmorPenetrationPercent": 1.0,
			"bonusMagicPenetrationPercent": 1.0,
			"critChance": 0.20000000298023225,
			"critDamage": 175.0,
			"currentHealth": 2343.0,
			"healShieldPower": 0.0,
			"healthRegenRate": 46.2239990234375,
			"lifeSteal": 0.0,
			"magicLethality": 0.0,
			"magicPenetrationFlat": 0.0,
			"magicPenetrationPercent": 1.0,
			"magicResist": 61.25,
			"maxHealth": 2343.0,
			"moveSpeed": 431.0,
			"omnivamp": 0.0,
			"physicalLethality": 70.0,
			"physicalVamp": 0.0,
			"resourceMax": 1007.0000610351563,
			"resourceRegenRate": 18.288000106811525,
			"resourceType": "MANA",
			"resourceValue": 1007.0000610351563,
			"spellVamp": 0.0,
			"tenacity": 0.0
		},
		"currentGold": 10995.06640625,
		"fullRunes": {
			"generalRunes": [
				{
					"displayName": "Electrocute",
					"id": 8112,
					"rawDescription": "perk_tooltip_Electrocute",
					"rawDisplayName": "perk_displayname_Electrocute"
				},
				{
					"displayName": "Sudden Impact",
					"id": 8143,
					"rawDescription": "perk_tooltip_SuddenImpact",
					"rawDisplayName": "perk_displayname_SuddenImpact"
				},
				{
					"displayName": "Eyeball Collection",
					"id": 8138,
					"rawDescription": "perk_tooltip_EyeballCollection",
					"rawDisplayName": "perk_displayname_EyeballCollection"
				},
				{
					"displayName": "Ultimate Hunter",
					"id": 8106,
					"rawDescription": "perk_tooltip_UltimateHunter",
					"rawDisplayName": "perk_displayname_UltimateHunter"
				},
				{
					"displayName": "Nimbus Cloak",
					"id": 8275,
					"rawDescription": "perk_tooltip_NimbusCloak",
					"rawDisplayName": "perk_displayname_NimbusCloak"
				},
				{
					"displayName": "Gathering Storm",
					"id": 8236,
					"rawDescription": "perk_tooltip_GatheringStorm",
					"rawDisplayName": "perk_displayname_GatheringStorm"
				}
			],
			"keystone": {
				"displayName": "Electrocute",
				"id": 8112,
				"rawDescription": "perk_tooltip_Electrocute",
				"rawDisplayName": "perk_displayname_Electrocute"
			},
			"primaryRuneTree": {
				"displayName": "Domination",
				"id": 8100,
				"rawDescription": "perkstyle_tooltip_7200",
				"rawDisplayName": "perkstyle_displayname_7200"
			},
			"secondaryRuneTree": {
				"displayName": "Sorcery",
				"id": 8200,
				"rawDescription": "perkstyle_tooltip_7202",
				"rawDisplayName": "perkstyle_displayname_7202"
			},
			"statRunes": [
				{
					"id": 5008,
					"rawDescription": "perk_tooltip_StatModAdaptive"
				},
				{
					"id": 5008,
					"rawDescription": "perk_tooltip_StatModAdaptive"
				},
				{
					"id": 5003,
					"rawDescription": "perk_tooltip_StatModMagicResist"
				}
			]
		},
		"level": 18,
		"summonerName": "DrMeteor"
	},
	"allPlayers": [
		{
			"championName": "Kha'Zix",
			"isBot": false,
			"isDead": false,
			"items": [
				{
					"canUse": false,
					"consumable": false,
					"count": 1,
					"displayName": "Duskblade of Draktharr",
					"itemID": 6691,
					"price": 1000,
					"rawDescription": "GeneratedTip_Item_6691_Description",
					"rawDisplayName": "Item_6691_Name",
					"slot": 0
				},
				{
					"canUse": false,
					"consumable": false,
					"count": 1,
					"displayName": "Edge of Night",
					"itemID": 3814,
					"price": 1050,
					"rawDescription": "GeneratedTip_Item_3814_Description",
					"rawDisplayName": "Item_3814_Name",
					"slot": 1
				},
				{
					"canUse": false,
					"consumable": false,
					"count": 1,
					"displayName": "The Collector",
					"itemID": 6676,
					"price": 425,
					"rawDescription": "GeneratedTip_Item_6676_Description",
					"rawDisplayName": "Item_6676_Name",
					"slot": 2
				},
				{
					"canUse": true,
					"consumable": false,
					"count": 1,
					"displayName": "Youmuu's Ghostblade",
					"itemID": 3142,
					"price": 700,
					"rawDescription": "GeneratedTip_Item_3142_Description",
					"rawDisplayName": "Item_3142_Name",
					"slot": 3
				},
				{
					"canUse": false,
					"consumable": false,
					"count": 1,
					"displayName": "Serpent's Fang",
					"itemID": 6695,
					"price": 625,
					"rawDescription": "GeneratedTip_Item_6695_Description",
					"rawDisplayName": "Item_6695_Name",
					"slot": 4
				},
				{
					"canUse": false,
					"consumable": false,
					"count": 1,
					"displayName": "Ionian Boots of Lucidity",
					"itemID": 3158,
					"price": 650,
					"rawDescription": "GeneratedTip_Item_3158_Description",
					"rawDisplayName": "Item_3158_Name",
					"slot": 5
				},
				{
					"canUse": true,
					"consumable": false,
					"count": 1,
					"displayName": "Stealth Ward",
					"itemID": 3340,
					"price": 0,
					"rawDescription": "GeneratedTip_Item_3340_Description",
					"rawDisplayName": "Item_3340_Name",
					"slot": 6
				}
			],
			"level": 18,
			"position": "",
			"rawChampionName": "game_character_displayname_Khazix",
			"rawSkinName": "game_character_skin_displayname_Khazix_4",
			"respawnTimer": 0.0,
			"runes": {
				"keystone": {
					"displayName": "Electrocute",
					"id": 8112,
					"rawDescription": "perk_tooltip_Electrocute",
					"rawDisplayName": "perk_displayname_Electrocute"
				},
				"primaryRuneTree": {
					"displayName": "Domination",
					"id": 8100,
					"rawDescription": "perkstyle_tooltip_7200",
					"rawDisplayName": "perkstyle_displayname_7200"
				},
				"secondaryRuneTree": {
					"displayName": "Sorcery",
					"id": 8200,
					"rawDescription": "perkstyle_tooltip_7202",
					"rawDisplayName": "perkstyle_displayname_7202"
				}
			},
			"scores": {
				"assists": 0,
				"creepScore": 120,
				"deaths": 0,
				"kills": 0,
				"wardScore": 2.25
			},
			"skinID": 4,
			"skinName": "Dark Star Kha'Zix",
			"summonerName": "DrMeteor",
			"summonerSpells": {
				"summonerSpellOne": {
					"displayName": "Flash",
					"rawDescription": "GeneratedTip_SummonerSpell_SummonerFlash_Description",
					"rawDisplayName": "GeneratedTip_SummonerSpell_SummonerFlash_DisplayName"
				},
				"summonerSpellTwo": {
					"displayName": "Smite",
					"rawDescription": "GeneratedTip_SummonerSpell_SummonerSmite_Description",
					"rawDisplayName": "GeneratedTip_SummonerSpell_SummonerSmite_DisplayName"
				}
			},
			"team": "ORDER"
		}
	],
	"events": {
		"Events": [
			{
				"EventID": 0,
				"EventName": "GameStart",
				"EventTime": 0.02188129909336567
			},
			{
				"EventID": 1,
				"EventName": "MinionsSpawning",
				"EventTime": 65.03199005126953
			},
			{
				"Assisters": [],
				"EventID": 2,
				"EventName": "TurretKilled",
				"EventTime": 290.8241882324219,
				"KillerName": "DrMeteor",
				"TurretKilled": "Turret_T2_L_03_A"
			},
			{
				"EventID": 3,
				"EventName": "FirstBrick",
				"EventTime": 290.8241882324219,
				"KillerName": "DrMeteor"
			},
			{
				"Assisters": [],
				"DragonType": "Water",
				"EventID": 4,
				"EventName": "DragonKill",
				"EventTime": 323.1292724609375,
				"KillerName": "DrMeteor",
				"Stolen": "False"
			},
			{
				"Assisters": [],
				"EventID": 5,
				"EventName": "TurretKilled",
				"EventTime": 444.2792663574219,
				"KillerName": "DrMeteor",
				"TurretKilled": "Turret_T2_R_03_A"
			}
		]
	},
	"gameData": {
		"gameMode": "PRACTICETOOL",
		"gameTime": 542.0155029296875,
		"mapName": "Map11",
		"mapNumber": 11,
		"mapTerrain": "Default"
	}
}
```

**Comment by MingweiSamuel** [comment]
Ok, I've updated the schema generation so all the `PlayerChampionStats` fields and some other fields are doubles instead of ints, https://www.nuget.org/packages/Camille.LolGame/3.0.0-nightly-2021-10-24-934f6e9d93

**Comment by diogotr7** [comment]
That seems to work, thanks! If i come across any other problem i'll make a new issue.
